### ISSUE TITLE
Highlight completely broken after a heredoc whose content are purely variables

### ISSUE THREAD

**Issue by willww64** [tree-sitter/tree-sitter-bash#98]
![Screenshot_20210512_164308](https://user-images.githubusercontent.com/9930358/117946868-42829680-b342-11eb-8a1e-94dc1bdbe93a.png)
![Screenshot_20210512_164409](https://user-images.githubusercontent.com/9930358/117946866-41ea0000-b342-11eb-9b69-b370d5df818e.png)
![Screenshot_20210512_164548](https://user-images.githubusercontent.com/9930358/117946861-41516980-b342-11eb-8f24-c0cf7454a80a.png)
![Screenshot_20210512_164642](https://user-images.githubusercontent.com/9930358/117946855-40203c80-b342-11eb-92d9-c9e8c5f64d08.png)

As shown in the second and third screenshot, all content after the heredoc are highlighted as string.

**Comment by willww64** [comment]
As of today, I noticed that this issue has been fixed.

**Comment by PowerUser64** [comment]
Hmm, I still see it

![image](https://user-images.githubusercontent.com/24578572/164188463-e4f33b52-abb2-424c-b8ac-e716f441f180.png)

**Comment by dumblob** [comment]
I am having the same/similar issue with nested heredoc constructs.

**Comment by amaanq** [comment]
Just fixed nested heredocs on master, thanks

**Comment by pillzu** [comment]
Not sure but I still see this issue on my end. I tried doing a `:TSUpdate` but all parsers seems up to date.

**Comment by amaanq** [comment]
sorry, but neovim-related issues don't belong here, if the *parse* output is failing/incorrect then that's an issue here
